### ISSUE TITLE
[PdfStatistics] Library to get statistics about pdf file

### ISSUE THREAD

**Issue by krzysztofruszczynski** [EmchBerger/cube-common-bundle#29]
Library can get info about:
- size of pages
- format of pages 
- which pages are in color

**Comment by SimonHeimberg** [comment]
can we close this? it is in 1.0.20

**Comment by krzysztofruszczynski** [comment]
I enhanced pdf statistics and created image statistics based on that. After that changes are applied, we can close this.

**Comment by SimonHeimberg** [comment]
included in 1.1

remaining: #58
