### ISSUE TITLE
[phpexcel] make dependency on phpexcel really optional

### ISSUE THREAD

**Issue by mschafr** [EmchBerger/cube-common-bundle#43]
When using cube-common-bundle in another project, I get the error message as follows:
<code>
    The service "cube_common.excel.converter" has a dependency on a non-existent service "phpexcel".
</code>

I assume this is missing in the composer.json as dependency.
Version: 1.0.21

**Comment by markussc** [comment]
I see it's mentioned as "suggested". Hmmm... is this the way such dependencies are usually handled? I was not given this suggestion during composer update.

**Comment by SimonHeimberg** [comment]
The idea is that the bundle can be used without phpexcel. But this seems not to work. To be solved ....

suggestions should be shown when running `composer require cubetools/cube-common-bundle`, or `composer suggests`
