### ISSUE TITLE
[GitVersion] there is a dependency on CUBE PA's DashboardController

### ISSUE THREAD

**Issue by markussc** [EmchBerger/cube-common-bundle#44]
<code>An exception has been thrown during the rendering of a template ("The _controller value "AppBundle:Dashboard:getGitVersion" maps to a "AppBundle\Controller\DashboardController" class, but this class was not found. Create this class or check the spelling of the class and its namespace.").</code>

Version: 1.0.21

**Comment by SimonHeimberg** [comment]
The problem must be in the project. No template (nor any other code) contains a reference to .\*GitVersion.\* or .\*gitversion.\*.
