### ISSUE TITLE
[FileStatistics] Increase pdf / image analysis speed

### ISSUE THREAD

**Issue by MartinRosserEB** [EmchBerger/cube-common-bundle#58]
Analysis of ten reasonably small PDFs takes 24.6 seconds. This makes it difficult to use such features in a responsive web app. The feature is still very useful for offline analysis though.

**Comment by krzysztofruszczynski** [comment]
We can use linux "identify" command via php exec command. It shows us number of pages and format, but I don't think we can recognize whether document is grayscale or in color. Looks to work faster, but it still needs 1.5-2 seconds for one page document to analyse.

**Comment by krzysztofruszczynski** [comment]
As discussed, we can write info about file format, color and number of pages directly by Document Entity and use this data when print is requested.

**Comment by krzysztofruszczynski** [comment]
Getting format of all sites in document ( 38 pages,  ~5 MB also with pictures ) via Imagick:

readImage 11.279 s
pingImage 4.47 s

As @SimonHeimberg mentioned, we can't use this function to decide whether document is in colour other grayscale.

**Comment by MartinRosserEB** [comment]
Documents are now analysed offline, results written in database. This ticket is not needed any longer.
