### ISSUE TITLE
[EntityHistory] service to store logging information into entites

### ISSUE THREAD

**Issue by markussc** [EmchBerger/cube-common-bundle#7]
Entities containing a method called "historicizedFields" (or similar) and contain a field "entityHistory" can be logged with 2 simple calls:
- before changing the entity, initialize the entityHistory service with the entity. Before flushing, pass the entity again with the new status. The service will return an array with the diff and update the entityHistory field of the entity.

**Comment by SimonHeimberg** [comment]
maybe we should look at [loggable from DoctrineExtensions](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/loggable.md)

If we do with entityHistory service, `historicizedFields()` should be in an interface.

**Comment by MartinRosserEB** [comment]
@krzysztofruszczynski see here for info on loggable

**Comment by MartinRosserEB** [comment]
Other options are:

- https://github.com/DATA-DOG/DataDogAuditBundle
- https://github.com/simplethings/EntityAuditBundle

**Comment by SimonHeimberg** [comment]
logging implemented in since #1308 is fixed. What is still current?
