### ISSUE TITLE
[branch naming] version branches

### ISSUE THREAD

**Issue by MartinRosserEB** [EmchBerger/cube-common-bundle#94]
- Why are there releases on development branch? Specifically https://github.com/EmchBerger/cube-common-bundle/commit/8e0f0ccd6eacfe4749060585b7a10553313c5a7b
- Why do we have v1.0 branch but no other version branches? I assume: We will create a version branch for v2 (suggest omitting .0) once it exists.
- If my assumption above is not correct: Why are there no branches for v1.1, v1.2, ...?

**Comment by SimonHeimberg** [comment]
I suggest to only have two long living branches: development and master. Master for bugfixing, development for new features.
Maybe we would need a branch for v1 and one for v2, but in between, updating is possible without any problem
